# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StateMessage.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12StateMessage.proto\x12\x15pyspark.sql.streaming\"\xc3\x01\n\x0cStateRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12Y\n\x1bstatefulProcessorHandleCall\x18\x02 \x01(\x0b\x32\x32.pyspark.sql.streaming.StatefulProcessorHandleCallH\x00\x12=\n\rlistStateCall\x18\x03 \x01(\x0b\x32$.pyspark.sql.streaming.ListStateCallH\x00\x42\x08\n\x06method\"9\n\rStateResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\"\xa5\x01\n\x1bStatefulProcessorHandleCall\x12?\n\x0esetHandleState\x18\x02 \x01(\x0b\x32%.pyspark.sql.streaming.SetHandleStateH\x00\x12;\n\x0cgetListState\x18\x03 \x01(\x0b\x32#.pyspark.sql.streaming.GetListStateH\x00\x42\x08\n\x06method\"1\n\x0cGetListState\x12\x11\n\tstateName\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\"\xa6\x01\n\rListStateCall\x12/\n\x06\x65xists\x18\x01 \x01(\x0b\x32\x1d.pyspark.sql.streaming.ExistsH\x00\x12)\n\x03get\x18\x02 \x01(\x0b\x32\x1a.pyspark.sql.streaming.GetH\x00\x12/\n\x06update\x18\x03 \x01(\x0b\x32\x1d.pyspark.sql.streaming.UpdateH\x00\x42\x08\n\x06method\"\x08\n\x06\x45xists\"\x18\n\x03Get\x12\x11\n\tstateName\x18\x01 \x01(\t\"\x08\n\x06Update\"C\n\x0eSetHandleState\x12\x31\n\x05state\x18\x01 \x01(\x0e\x32\".pyspark.sql.streaming.HandleState*K\n\x0bHandleState\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0f\n\x0bINITIALIZED\x10\x01\x12\x12\n\x0e\x44\x41TA_PROCESSED\x10\x02\x12\n\n\x06\x43LOSED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StateMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDLESTATE']._serialized_start=805
  _globals['_HANDLESTATE']._serialized_end=880
  _globals['_STATEREQUEST']._serialized_start=46
  _globals['_STATEREQUEST']._serialized_end=241
  _globals['_STATERESPONSE']._serialized_start=243
  _globals['_STATERESPONSE']._serialized_end=300
  _globals['_STATEFULPROCESSORHANDLECALL']._serialized_start=303
  _globals['_STATEFULPROCESSORHANDLECALL']._serialized_end=468
  _globals['_GETLISTSTATE']._serialized_start=470
  _globals['_GETLISTSTATE']._serialized_end=519
  _globals['_LISTSTATECALL']._serialized_start=522
  _globals['_LISTSTATECALL']._serialized_end=688
  _globals['_EXISTS']._serialized_start=690
  _globals['_EXISTS']._serialized_end=698
  _globals['_GET']._serialized_start=700
  _globals['_GET']._serialized_end=724
  _globals['_UPDATE']._serialized_start=726
  _globals['_UPDATE']._serialized_end=734
  _globals['_SETHANDLESTATE']._serialized_start=736
  _globals['_SETHANDLESTATE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
